version: "3.1"

volumes:
  postgres:
    external: true

services:
    postgres:
      image: postgres
      container_name: ${PROJECT_NAME}-postgres
      volumes:
        - postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
       - "5432:5432"

    webserver:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver
      working_dir: /backend
      volumes:
          - ./backend:/backend
          - ./docker/nginx:/etc/nginx/conf.d
      ports:
       - "80:80"
      depends_on:
        - postgres
        - php-fpm

    php-fpm:
      build: docker/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /backend
      volumes:
        - ./backend:/backend
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      depends_on:
        - postgres